### PR TITLE
Upgrade to Angular@2.1.0 and Handsontable@0.26

### PR DESCRIPTION
**Pull request by renehamburger**
The update to Angular@2.1.0 required quite a few changes, but the API is now stable and any further updates should be painless. I've updated many of the other modules along the way, some of which was necessitated by the newer Angular and TypeScript.

The main change in the newest Handsontable is its use of a module loader instead of a global variable.

### CODE REVIEW

**Comment by syriuszp** [comment]
@renehamburger appreciate your support for ng2-handsontable, Can you somehow forecast when you will finalise upgarde to Angular@2.1.0 and make merge >

**Comment by renehamburger** [comment]
@valorkin, are you able to merge this some time this week? Anything I can do to make it happen?

There are a few more important changes in the pipeline, like running handsontable outside the Angular zone (see https://github.com/renehamburger/ng2-handsontable/compare/master...renehamburger:develop).

**Comment by ralberts** [comment]
@renehamburger I am curious - if I wanted to get this working with your changes - do you have any additional changes or forks of this code that work with the latest angular?

**Comment by valorkin** [comment]
It is obvious that I am completely out of time , if some one would love to maintain this Lib, I will gladly give all required access. Sorry folks >.}

**Comment by renehamburger** [comment]
@valorkin, I'd be happy to help out. Are you able to provide some guidelines on the failing CI tests?

**Comment by valorkin** [comment]
Find me in slack https://ngx-slack.herokuapp.com
I am responding there faster

**Pull request merged**
